version: '3.8'
networks:
  postgresql-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
  postgresql:
    image: postgres:14
    container_name: dockerpostgresql
    restart: always
    networks:
      - postgresql-network
    environment:
      - POSTGRES_USER=${__YOUR_DATABASE_USER__}
      - POSTGRES_PASSWORD=${__YOUR_DATABASE_PASSWORD__}
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    mem_limit: 512m
  prisma:
    container_name: dockerprisma
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - postgresql-network
    command: >
      bash -c '
        npx prisma db push --schema prisma/schema.prisma
        npm start
      '
    depends_on:
      - postgresql
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${__YOUR_MANAGEMENT_API_SECRET__}
        port: ${__YOUR_PRISMA_SERVER_PORT__}
        databases:
          default:
            connector: ${__YOUR_DATABASE_CONNECTOR__}
            host: ${__YOUR_DATABASE_HOST__}
            port: ${__YOUR_DATABASE_PORT__}
            user: ${__YOUR_DATABASE_USER__}
            password: ${__YOUR_DATABASE_PASSWORD__}
            connectionLimit: ${__YOUR_CONNECTION_LIMIT__}
    mem_limit: 512m
volumes:
  data-prisma:
  data-postgresql:

# version: '3'
# services:
#   app:
#     container_name: estagio_legal_back
#     build: .
#     depends_on:
#       - database
#     ports:
#       - ${DOCKER_PORT}:${API_PORT}
#     environment:
#       DATABASE_URL: ${DATABASE_URL}
#   database:
#     container_name: estagio_legal_db
#     image: postgres
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     ports:
#     - ${DB_PORT}:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata: